### ISSUE TITLE
Going back in time not working on Safari

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/daqview-react#15]
Hi,

I cannot go to past snapshots when using Safari. Neither the arrows work, nor if I specify a timestamp in the field or the URL. I always get 'Monitoring data unavailable: Could not find snapshot'. It works flawlessly on Chrome.

Cheers,
Remi

**Comment by mvougiou** [comment]
Hi,

I suppose the go-to-time also does not work (since all actions with date/time eventually use this input). I would imagine Safari has different implementation of the Date parser. I can further investigate, if it is possible to install Safari on SLC6.

**Comment by Phil2812** [comment]
Can you please check if this works now? I made a change recently to support older versions of Firefox, which might have solved this as well.

**Comment by mommsen** [comment]
It indeed works now on Safari. Thanks.

Remi
