### ISSUE TITLE
add a link from daqview back to the DAQ expert browser

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/daqview-react#25]
this would allow going back and forth quickly between failures seen in the DAQ view archive and the timeline of the DAQ Expert to better understand the analysis done by the DAQ Expert.

**Comment by Phil2812** [comment]
Implemented in 36657c9457642d240d5e5c58c998d82fcffd703d

The link points to the expert browser with the current snapshot in the center of the view and 5 minutes before and after it. Please check if these settings are acceptable:
http://daq-expert-dev.cms/daq2view-react/index.html?setup=testbed

**Comment by andreh12** [comment]
thanks a lot ! 

I had a quick look and it works for me, both with the current time and a time 24h in the past.

I guess we can close this ticket ?

**Comment by Phil2812** [comment]
Thanks for the feedback.
