### ISSUE TITLE
FFF and FB table button links do not include time url parameter 

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/daqview-react#31]
As a consequence, when following a link pointing to a past point in time and clicking e.g. on the FFF button one suddenly sees the current status instead of the historical one.

They do however include the `cdaq` parameter.

**Comment by andreh12** [comment]
is this the relevant part of the code where the `time` parameter (if set) should be added

https://github.com/cmsdaq/daqview-react/blob/50f14150476c4ed77cb3b5a80c71f79448876308/index_fb.html#L311

?

**Comment by Phil2812** [comment]
Yes, it is the relevant part of the code. But we have pending changes to the index on my fork.

If this is in fact desired behavior, I can make the change and create a pull request.

**Comment by Phil2812** [comment]
Implemented in 7b46740289b2edb1bc6f1f202d5e424fe881c288
