### ISSUE TITLE
Incompatibility with previous snapshot format

### ISSUE THREAD

**Issue by Phil2812** [cmsdaq/daqview-react#36]
Do we have a policy regarding backwards-compatibility of the DAQView? I remember it being brought up during the initial discussions, but don't recall what we agreed on.

Since the instantaneous deadtimes are available in snapshots now, the deadtime table is no longer compatible with snapshots that do not yet contain this data, even if they do contain the deadtime per lumisection. As it is, a message saying that there was no deadtime information found in the snapshot will be displayed for old snapshots. Is this the desired behavior? Or is the DAQView supposed to display per lumisection data if available instead?

I think we can agree that:
1) DAQView should be compatible with the old format if the new format only contains additional data, for example by displaying a message that some data is unavailable. This needs to be done anyway, since test setups usually do not produce full snapshots.

What I am not sure about:
2) What is the desired behavior if snapshot attributes get renamed or the snapshot structure changes?
3) The case described above, where additional data is added to the snapshot and the old format contains compatible data.

**Comment by hsakulin** [comment]
The desired behavior in this case:

- If instant values are in the snapshot: Use them and put “ (Instant)” after the row headings for Deadtime/Beamactive Deadtime.
- If instant values are NOT in the snapshot: Use the per LS values and put “ (last LS)” after the row headings.

**Comment by Phil2812** [comment]
What I described is not actually the case. Since the snapshot is serialized again by the snapshot service, it always includes the instant dead times, yet the object is simply empty for older snapshots. This makes it more difficult to detect in a clean way and does not lead to the error message mentioned, but to "N/A" displayed in all the deadtime fields of the table.

**Comment by Phil2812** [comment]
Implemented in 3baccfef440289500d80e9f9f9fcca32a0769567
Instant example:
http://daq-expert-dev.cms/daq2view-react/index_fb_dt.html?setup=testbed&time=2017-11-08-15:05:41
Last LS example:
http://daq-expert-dev.cms/daq2view-react/index_fb_dt.html?setup=testbed&time=2017-10-04-14:30:04

**Comment by hsakulin** [comment]
Looks good!
